Nesh admin projects page
bazaTraineeUkraine/baza-trainee pull request #128
Opened 2023-09-27 22:33 UTC by Neschadin

2023-09-28 08:59 UTC, Fstv-Electro commented on src/utils/API/projects.ts
> +        console.log('API res >>', res.data);
прибрати консоль логи

2023-09-28 09:01 UTC, Fstv-Electro approved these changes

2023-09-28 09:08 UTC, Fstv-Electro requested changes
change prop route.back to reset form

2023-09-28 09:30 UTC, Mazayw requested changes
Написав в Discord

2023-09-29 09:20 UTC, Fstv-Electro approved these changes

2023-09-29 09:32 UTC, Fstv-Electro approved these changes

2023-09-29 17:04 UTC, Mazayw approved these changes

2023-09-29 17:05 UTC, merged