Add open card menu
bazaTraineeUkraine/baza-trainee pull request #22
Opened 2023-06-03 18:40 UTC by dianaforost

Додала логіку відкриття та закриття доддкової інформації про команду на карточках з поміткою "Завершено". Стилізувала скроллбар, на посилання членів команди мають бути їх аккаунти в linkedIn, поки що поставила як заглушку посилання на головну сторінку linkedIn. На кожне посилання поставила target="_blank" щоб користувач не втрачав зв'язок з нашим сайтом і посилання відкривалось на наступній вкладці. Також додала referrerpolicy="no-referrer" задля безпеки. У стилях скроллбара додала стилі для Firefox, але не тестила.

2023-06-03 19:02 UTC, Mazayw reviewed
В стилях використовуються абсолютні і відносні величини, була омоленість про використання лише відносних

Можливо, тут додати відступи знизу?
![image](https://github.com/baza-trainee/baza-trainee-landing/assets/20990494/c41e590e-43a2-446b-b683-fa77b5eb9b87)

2023-06-03 21:09 UTC, dianaforost commented
> В стилях выдерживается абсолютная и відносні величина, була домовленность про використання лише відносних
> 
> Можливо, тут додати відступи знизу? ![изображение](https://user-images.githubusercontent.com/20990494/243126074-c41e590e-43a2-446b-b683-fa77b5eb9b87.png)

Вибачте, можливо пропустила обговорення щодо цього. Я правильно розумію, що треба прибрати всі postition:absolute і переписати стилі?  А на рахунок паддінгів - то так на макеті є. тому я так і зробила

2023-06-03 21:28 UTC, dianaforost commented
> В стилях використовуються абсолютні і відносні величини, була домовленість про використання лише відносних
> 
> Можливо, тут додати відступи знизу? ![image](https://user-images.githubusercontent.com/20990494/243126074-c41e590e-43a2-446b-b683-fa77b5eb9b87.png)

Хоча Дмитро і Наталя приймали в мене код і нічого не казали за це. Плюс є секції(наприклад в хедері кнопка зміну мови, або в секції відгуки) де є ці position relative та absolute. Що ж робити?

2023-06-03 21:35 UTC, dianaforost commented
> В стилях використовуються абсолютні і відносні величини, була домовленість про використання лише відносних
> 
> Можливо, тут додати відступи знизу? ![image](https://user-images.githubusercontent.com/20990494/243126074-c41e590e-43a2-446b-b683-fa77b5eb9b87.png)

Або ви маєте на увазі відсотки?

2023-06-04 08:46 UTC, Mazayw requested changes

2023-06-04 08:46 UTC, Mazayw commented on src/scss/layout/_projects.scss
> +    &__container{
Рядки 201 та 230 частково дублюються однаковим селектором

2023-06-04 08:46 UTC, Mazayw commented on src/scss/layout/_projects.scss
> +    .thumb__container {
Можливо, краще змінити, для збереження стилю коду?
```css
.thumb__container {
        scrollbar-width: 0.8rem;
        
        &::-webkit-scrollbar-thumb {
            background: $color-white;
            border-radius: 0.4rem;
        }
        
        &::-webkit-scrollbar-track {
            background: $linear-gradient-white;
        }
    }
```

2023-06-04 12:42 UTC, dianaforost commented on src/scss/layout/_projects.scss
> +    .thumb__container {
Виправила!

2023-06-04 15:57 UTC, NataPas2021 approved these changes

2023-06-04 16:06 UTC, Mazayw approved these changes

2023-06-04 16:06 UTC, merged