fix: projects style
bazaTraineeUkraine/baza-trainee pull request #28
Opened 2023-06-07 13:06 UTC by dianaforost

Пофіксила стилі. Додала лінк сайту, та змінила imageUrl. Також додала до кожного юзера лінк на лінкедін, потім там має бути лінки на їх аккаунти на цій платформі. Додала пошук.

2023-06-07 14:40 UTC, Mazayw requested changes
svg краще винести в окремий компонент до папки components/common/icons, це зробить код більш чистим та спростить його розуміння

2023-06-07 14:40 UTC, Mazayw commented on src/components/common/ProjectCard/index.tsx
> +    teamButtons.forEach((button) => {
Ця функція буде працювати з помилками, тому що назва стилів генерується автоматично

2023-06-07 14:40 UTC, Mazayw commented on src/components/common/ProjectCard/index.tsx
> +  const formatDate = (dateString: string) => {
Такі функції (допоміжні функції) краще виносити в окремі файли в src\utils
Це зробить код чистішим

2023-06-07 14:40 UTC, Mazayw commented on src/components/common/ProjectCard/index.tsx
Цей компонент повинен займатися лише рендером однієї картки проєкту, тому що він буде використовуватися на головній сторінці та в адмінці

2023-06-07 14:40 UTC, Mazayw commented on src/components/common/ProjectCard/styles.module.scss
>  @import '../../../styles/abstracts/_variables.scss';
Цей імпорт вже не потрібен. В одному з попередніх ПР був зроблений його автоматичний імпорт в усі файли-стилів

2023-06-09 16:59 UTC, Mazayw requested changes
Папка src/components/common призначена для компонентів які (будуть) використовуються в інших компонентах. Якщо цей компонент використовуються лише в одному компоненті. Його краще розміщати поряд з головним компонентом, це спростить розуміння коду та пошук(навігацію) в проекті

2023-06-09 16:59 UTC, Mazayw commented on src/components/MainPage/Projects/index.tsx
> +              <ProjectCard key={generateRandomNumber()} project={project} />
Ключ повинен бути унікальним, і його краще брати з об'єкту який передається в map(). В даному випадку, для прикладу, є _id, або будь-який інший унікальний ключ - він краще підійде в якості ключа.
Розробники Реакту не рекомендують використовувати випадкове число, індекс масиву і т.д. в якості ключа

2023-06-09 16:59 UTC, Mazayw commented on src/components/common/ProjectCard/index.tsx
> +  function generateRandomNumber() {
Ця функція непотрібна

2023-06-09 16:59 UTC, Mazayw commented on src/components/common/ProjectCard/index.tsx
> +      <li key={generateRandomNumber()}>
key не потрібен в компоненті, який ітерується

2023-06-09 16:59 UTC, Mazayw commented on src/components/common/ProjectCard/index.tsx
> +  const onClick = () => {
Назви змінних повинні описувати що вони роблять, або що там зберігається. Для прикладу showTeamHandler

2023-06-09 16:59 UTC, Mazayw commented on src/components/common/ProjectCard/index.tsx
> +  const [isOpen, setIsOpen] = useState(false);
Назви змінних повинні описувати що вони роблять
isOpen - для прикладу, більш зрозуміло було isTeamShow
isOpen - не зрозуміло за що відповідає змінна

2023-06-09 16:59 UTC, Mazayw commented on src/components/common/ProjectCard/index.tsx
> +          style={{
Для чого використовуються інлайн стилі та класи в одному тезі?

2023-06-09 16:59 UTC, Mazayw commented on src/utils/projectCycle.ts
Назви повинні описувати що виконує компонент/функція і т.д.
Для прикладу developmentTimeCalculator

2023-06-09 16:59 UTC, Mazayw commented on src/utils/renderFilledDivs.tsx
Це не допоміжна функція а компонент (є розмітка - .tsx). Варто змінити папку, або змінити функцію
Спробуй спростити цю функцію, так як ми обговорювали на колі

2023-06-09 16:59 UTC, Mazayw commented on src/utils/renderFilledDivs.tsx
> +          key={i}
key не потрібен

2023-06-09 16:59 UTC, Mazayw commented on src/utils/renderTeamMembersByRole.tsx
> +  function generateRandomNumber() {
generateRandomNumber заборонено в якості ключа - це може викликати баги при рендері

2023-06-09 16:59 UTC, Mazayw commented on src/utils/renderTeamMembersByRole.tsx
> +                key={generateRandomNumber()}
https://react.dev/learn/rendering-lists

2023-06-09 16:59 UTC, Mazayw commented on src/components/common/ProjectCardStatus/index.tsx
> +              key={status.id}
Ключ не може бути однаковим

2023-06-09 17:13 UTC, dianaforost commented on src/components/MainPage/Projects/index.tsx
> +              <ProjectCard key={generateRandomNumber()} project={project} />
Справа в тому, що мені скаржиться на те, що ключі в массиву обьєктів projects однакові.Тому я поки що зробила так. Я спробую виправити на айдішники projects і запушити.

2023-06-10 22:19 UTC, Mazayw requested changes

2023-06-10 22:19 UTC, Mazayw commented on src/components/common/ProjectCard/ProjectCardContent/index.tsx
> +import LevelIcon from '../../icons/LevelIcon';
Для збереження стилю краще замінити на :
@/components/common/icons/LevelIcon

2023-06-10 22:19 UTC, Mazayw commented on src/components/common/ProjectCard/ProjectCardContent/index.tsx
> +  onClick,
onClick- краще замінити на більш зрозумілу назву. 
Наприклад: switchCardInfo, showTeamHandler  або щось інше такого типу

2023-06-10 22:19 UTC, Mazayw commented on src/components/common/ProjectCard/ProjectCardContent/index.tsx
> +              {renderFilledDivs(project.complexity)}
Це компонент - він повинен називатися з великої літери

2023-06-10 22:19 UTC, Mazayw commented on src/components/common/ProjectCard/renderFilledDivs.tsx
Якщо створюється компонент в якому використовуються (імпортуються) стилі - поттрібно створювати окрему папку з компонентами і стилями для нього. Він повинен бути повністю незалежним.

2023-06-10 22:19 UTC, Mazayw commented on src/components/common/ProjectCard/renderFilledDivs.tsx
Краще змінити назву на більш зрозумілу. Наприклад ProjectStatus

2023-06-10 22:19 UTC, Mazayw commented on src/components/common/ProjectCard/index.tsx
> +    setShowTeamHandler(!showTeamHandler);
useState асинхронний, так змінювати стейт не можна 
setShowTeamHandler(!showTeamHandler) - в такому випадку висока ймовірність некоректного спрацьовування і будуть баги.
https://react.dev/reference/react/useState

2023-06-10 22:19 UTC, Mazayw commented on src/components/common/ProjectCard/renderTeamMembersByRole.tsx
> +    (member: any) => member.role.name === roleName
Any!)

2023-06-10 22:31 UTC, Mazayw requested changes

2023-06-10 22:31 UTC, Mazayw commented on src/components/common/ProjectCard/renderTeamMembersByRole.tsx
Краще винести в окрему папку компонент і стилі для даного компоненту.
Назви усіх компонентів повинні починатися з великої літери - TeamMembers
("render" - зайвий, тому що всі компоненти займаються рендером)

2023-06-12 18:45 UTC, Mazayw approved these changes

2023-06-12 18:47 UTC, merged