API
bazaTraineeUkraine/baza-trainee pull request #30
Opened 2023-06-14 16:32 UTC by SlipuyKamiN

2023-06-21 17:55 UTC, Mazayw requested changes

2023-06-21 17:55 UTC, Mazayw commented on src/utils/API/types.ts
> +export interface ILanguageSelector<T> {
Для чого тут джнерик? Здається, мова лише string

2023-06-21 17:55 UTC, Mazayw commented on src/utils/API/types.ts
> +  createdAt: Date;
createdAt: Date;
  updatedAt: Date;
Вже не потрібні

2023-06-21 17:55 UTC, Mazayw commented on src/utils/API/types.ts
Краще винести всі типи окремо /src/types/

2023-06-21 17:55 UTC, Mazayw commented on src/utils/hooks/useAPI.tsx
> +  const [data, setData] = useState<Object>({});
краще робити null, щоб бачити різницю між пустим об'єктом у відповіді та відсутністю даних

2023-06-21 17:55 UTC, Mazayw commented on src/utils/hooks/useAPI.tsx
> +  const [isError, setIsError] = useState<Object>(false);
isError - Object?

2023-06-21 17:55 UTC, Mazayw commented on src/utils/hooks/useAPI.tsx
> +    if (payload) {
Ти перевіряєш пейлоад до того як зроблено запит. Для чого?)

2023-06-21 17:55 UTC, Mazayw commented on src/utils/hooks/useAPI.tsx
> +        if (response.status === 200) {
Success статуси не обмежуються лише 200 кодом

2023-06-21 17:55 UTC, Mazayw commented on src/utils/hooks/useAPI.tsx
> +        setIsError(error);
Як варіант: можна було б дані помилки зберігати в дата //ти запитував про це

2023-06-21 17:55 UTC, Mazayw commented on src/utils/hooks/useAPI.tsx
> +  useEffect(() => {
Хорошою практикою є завершення запитів які очікують при анмаунті компонента

2023-06-22 08:48 UTC, SlipuyKamiN commented on src/utils/hooks/useAPI.tsx
> +  useEffect(() => {
У версії 2.0 зробив це у finally i при return теж, нез чи не зайве там буде, два рази

2023-06-22 16:37 UTC, Mazayw requested changes

2023-06-22 16:37 UTC, Mazayw commented on src/utils/hooks/useAPI.tsx
> +  baseURL: 'https://baza-trainee-7ain.onrender.com/',
Потрібно винести в окремий файл

2023-06-22 16:37 UTC, Mazayw commented on src/utils/hooks/useAPI.tsx
> +  const [isError, setIsError] = useState<Object | Boolean>(false);
isError - може бути об'єктом?

2023-06-22 16:37 UTC, Mazayw commented on src/utils/hooks/useAPI.tsx
Краще зробити типізацію за допомогою дженериків

2023-06-22 16:37 UTC, Mazayw commented on src/utils/hooks/useAPI.tsx
> +        if (response.status === 200 || response.status === 201) {
Як отримати причину помилки?

2023-06-28 11:48 UTC, Mazayw approved these changes

2023-06-28 11:48 UTC, Mazayw commented on src/types/typesAPI.ts
> +    en: String;
Краще винести в окремий тип/інтерфейс

2023-06-28 11:48 UTC, merged