feat: add sidebar
bazaTraineeUkraine/baza-trainee pull request #31
Opened 2023-06-16 11:23 UTC by YaroslavBoliachevets

2023-06-26 12:46 UTC, SlipuyKamiN requested changes

2023-06-26 12:46 UTC, SlipuyKamiN commented on src/components/Admin/Sidebar/index.tsx
> +    const a = localStorage.getItem('isAdminSideBarOpen');
при роботі з localeStorage рекомендується огортати в try...catch, бо це асинхронна операція

2023-06-26 12:46 UTC, SlipuyKamiN commented on src/components/Admin/Sidebar/index.tsx
> +    const a = localStorage.getItem('isAdminSideBarOpen');
при роботі з localeStorage рекомендується огортати в try...catch, бо це асинхронна операція

2023-06-26 12:46 UTC, SlipuyKamiN commented on src/components/Admin/Sidebar/MenuItem/SubmenuItem/styles.module.scss
> +  border-top: $border-black;
border bottom, бо вийшло так, що у кнопки "Стек" немає внизу, а по макету є.

2023-06-26 12:46 UTC, SlipuyKamiN commented on src/components/Admin/Sidebar/MenuItem/SubmenuItem/index.tsx
> +      id={id}
тут id вже не потрібен, бо ти під .map його проставляєш, на найвищому рівні. Хіба він десь використовується, що я не знайшов де.

2023-06-26 12:46 UTC, SlipuyKamiN commented on src/components/Admin/Sidebar/MenuItem/index.tsx
> +    <li id={id} className={styles['sidebar-list__item']} onClick={handleClick}>
те саме щодо id

2023-06-26 21:20 UTC, Mazayw commented on src/components/Admin/Sidebar/index.tsx
> +    const a = localStorage.getItem('isAdminSideBarOpen');
Ok

2023-06-26 21:20 UTC, Mazayw commented on src/components/Admin/Sidebar/index.tsx
> +    const a = localStorage.getItem('isAdminSideBarOpen');
Ok

2023-06-26 21:20 UTC, Mazayw commented on src/components/Admin/Sidebar/MenuItem/SubmenuItem/styles.module.scss
> +  border-top: $border-black;
БУла зміна макета. Виправив

2023-06-26 21:21 UTC, Mazayw commented on src/components/Admin/Sidebar/MenuItem/SubmenuItem/index.tsx
> +      id={id}
Потрібен, функція приймає id з тегу

2023-06-26 21:21 UTC, Mazayw commented on src/components/Admin/Sidebar/MenuItem/index.tsx
> +    <li id={id} className={styles['sidebar-list__item']} onClick={handleClick}>
те саме що й вище)

2023-06-27 04:08 UTC, SlipuyKamiN approved these changes

2023-06-27 04:08 UTC, merged