Admin base
bazaTraineeUkraine/baza-trainee pull request #32
Opened 2023-06-17 18:45 UTC by Mazayw

2023-06-18 14:02 UTC, SlipuyKamiN requested changes

2023-06-18 14:02 UTC, SlipuyKamiN commented on src/components/AdminPage/Authorization/index.tsx
> +  );
Тут варто передати колбек (()=>{return Boolean(...)})
В такому випадку, функція не буде викликатись на кожному ререндері, а тільки при монтуванні.

2023-06-18 14:02 UTC, SlipuyKamiN commented on src/components/AdminPage/Authorization/index.tsx
> +import auth from '@/utils/API/auth';
Там в папці АРІ в index.ts реекспорт, тобі тре імпортнути саме його, authAPI from ...../АРІ, бо я потім буду робити рефакторинг і вихідні змінні можуть змінитись, а саме змінні з реекспорта ні, там вже якщо authApi і все.

2023-06-18 14:02 UTC, SlipuyKamiN commented on src/components/AdminPage/Authorization/styles.module.scss
> +  width: 32.5rem;
По макету - ширше.

2023-06-18 14:02 UTC, SlipuyKamiN commented on src/components/common/InputFields/TextInput/styles.module.scss
> +  font-size: 1.8rem;
По макету 1,6

2023-06-18 17:03 UTC, Mazayw commented on src/components/AdminPage/Authorization/index.tsx
> +  );
В тому варіанті що є зараз значення isEnableRegister ініціалізується один раз при монтуванні компонента і залишається незмінним протягом життєвого циклу компонента. 
В запропонованому варіанті значення isEnableRegister оновлюється при кожному ререндері компонента.
ENABLE_REGISTRATION - це значення змінюється лише при зміні environment variables додатку

2023-06-18 17:29 UTC, Mazayw commented on src/components/AdminPage/Authorization/styles.module.scss
> +  width: 32.5rem;
Були зміни в макеті після верстки =/

2023-06-18 17:29 UTC, Mazayw commented on src/components/AdminPage/Authorization/index.tsx
> +import auth from '@/utils/API/auth';
Будемо робити реекспорт?

2023-06-19 17:26 UTC, SlipuyKamiN approved these changes

2023-06-19 17:27 UTC, merged