Context
bazaTraineeUkraine/baza-trainee pull request #33
Opened 2023-06-19 23:19 UTC by Mazayw

Додано стейт менеджмент
Реалізовано збереження вибору мови при перезавнтаженні
Обрана мова зберігається в глобальному стейті

2023-06-21 17:25 UTC, SlipuyKamiN requested changes

2023-06-21 17:25 UTC, SlipuyKamiN commented on src/components/MainPage/Header/index.tsx
> +        ? () => localStorage.getItem('lang') || 'ua'
| | "ua" не потрібен, в тебе вже нижче є : "ua", чи не так?

2023-06-21 17:25 UTC, SlipuyKamiN commented on src/components/common/ProjectCard/ProjectCardContent/index.tsx
> +  isMembersVIsible: boolean;
isMembersVisible

2023-06-21 17:25 UTC, SlipuyKamiN commented on src/components/common/ProjectCard/index.tsx
> +  const [isMembersVIsible, setIsMembersVIsible] = useState(false);
isMembersVisible

2023-06-21 17:57 UTC, Mazayw commented on src/components/common/ProjectCard/ProjectCardContent/index.tsx
> +  isMembersVIsible: boolean;
Це стосується іншого компоненту, я його не розробляв

2023-06-21 20:30 UTC, Mazayw commented on src/components/MainPage/Header/index.tsx
> +        ? () => localStorage.getItem('lang') || 'ua'
Потрібен. Спочатку йде перевірка де рендериться компонент - сервер чи броузер. Потім перевіряється чи є щось в локал сторейдж

2023-06-21 20:30 UTC, Mazayw commented on src/components/common/ProjectCard/index.tsx
> +  const [isMembersVIsible, setIsMembersVIsible] = useState(false);
Аналогічно)

2023-06-23 18:48 UTC, SlipuyKamiN approved these changes

2023-06-23 18:48 UTC, merged