Upgrade next.js; start refactor main page components; refactor globalStore; added Tailwind;
bazaTraineeUkraine/baza-trainee pull request #38
Opened 2023-06-28 19:32 UTC by Neschadin

upgraded next.js to 13.4.7 version;
added Tailwind;
started refactoring MainPage components;
changed useReducer to useState in globalStore;
added some icons (jsx style);

2023-06-28 20:57 UTC, Mazayw requested changes

2023-06-28 20:57 UTC, Mazayw commented on src/components/MainPage/HeroSlider/index.tsx
>  export type TSlide = {
Тип краще винести в папку з типами. Він ще буде використовуватися в адмінці

2023-06-28 20:57 UTC, Mazayw commented on src/components/MainPage/HeroSlider/index.tsx
> +const NextArrow = (props: CustomArrowProps) =>
Такі компоненти краще винести в окремий файл - так буде по Феншую)

2023-06-28 20:57 UTC, Mazayw commented on src/components/MainPage/HeroSlider/index.tsx
> +const PrevArrow = (props: CustomArrowProps) =>
Аналогічно

2023-06-28 20:57 UTC, Mazayw commented on src/components/MainPage/HeroSlider/slide.tsx
> +      style={{ backgroundImage: `url(${image})` }}
Можливо, краще через Next Image для оптимізацій?

2023-06-28 20:57 UTC, Mazayw commented on src/components/MainPage/Reviews/index.tsx
>    const SampleNextArrow = (props: any) => {
Аналогічно як і для попереднього слайдеру

2023-06-28 20:57 UTC, Mazayw commented on src/components/MainPage/Reviews/index.tsx
>    const SamplePrevArrow = (props: any) => {
Аналогічно як і для попереднього слайдеру

2023-06-28 20:57 UTC, Mazayw commented on src/utils/genKeyId.ts
Видалити)

2023-06-28 21:25 UTC, Neschadin commented
@Mazayw зараз нема сенсу рвью робить.  у нас же задача стоїть ввести таілвінд. а компоненти звісно шо до розуму доведу. тицяй зелену кнопку)

2023-06-29 05:59 UTC, Mazayw approved these changes

2023-06-29 05:59 UTC, merged