Footer
bazaTraineeUkraine/baza-trainee pull request #44
Opened 2023-07-04 20:16 UTC by SlipuyKamiN

2023-07-04 21:14 UTC, Mazayw requested changes
Потрібно пофіксити ссилки "Проєкти, Партнери, Взяти участь" - вони зараз не працюють.
Також, варто було б підключити отримання інформації з беку.

2023-07-04 21:14 UTC, Mazayw commented on src/components/MainPage/Footer/index.tsx
> +  { title: 'Політика конфіденційності', href: '/', underlined: true },
Стилі краще робити за допомогою селекторів CSS а не JS - так не ускладнюється код і не порушується відповідальність CSS-стилі, JS-логіка
Наприклад, селектор :nth-child(х)

2023-07-08 16:35 UTC, Neschadin requested changes

2023-07-08 16:35 UTC, Neschadin commented on src/components/MainPage/Footer/index.tsx
> +'use client';
жодна компонента лендінгу , яка містить якусь інфу, не повинна "виконуватись на стороні клієнта! 
в такому випадку про СЕО речі немає.

2023-07-08 16:35 UTC, Neschadin commented on src/components/MainPage/Footer/index.tsx
> +  ] = useAPI(contactsApi.getData);
якщо дійсно є небхідність отримати контакті данні з бд, то це треба робити на стороні сервера. бо тут не динамічне оновлення даних.
в цілому , якщо там всього декілька контактних данних, простіше захардкодити.

2023-07-08 16:35 UTC, Neschadin commented on src/components/MainPage/Footer/index.tsx
> +              className={`${styles['footer-list']} [&>*:nth-child(-n+2)]:underline`}
це ж тейлвіндом набагато простіше зробити.

2023-07-08 16:35 UTC, Neschadin commented on src/components/MainPage/Footer/index.tsx
> +              <li
донт репіт йоселф.  
закинь в о’єкт і  розмапити.

2023-07-08 16:35 UTC, Neschadin commented on src/components/MainPage/Footer/index.tsx
>              <ul
мені здається з точки зору семантики краще <nav> заюзати.

2023-07-21 16:16 UTC, Mazayw requested changes

2023-07-21 16:16 UTC, Mazayw commented on src/components/MainPage/Footer/index.tsx
> +    cache: 'no-cache',
Чому вимкнене кешування?

2023-07-21 16:16 UTC, Mazayw commented on src/components/MainPage/Footer/index.tsx
>  const anchoreLinksList = [
anchorLinksList

2023-07-21 16:16 UTC, Mazayw commented on src/components/MainPage/Footer/index.tsx
Краще було б робити не хардкодом, а через мап
Також, варто було б додавти перевірку, якщо немає даних - не виводити їх. n/a - недоречно, в даному випадку
Tailwind або модуль

2023-07-21 16:16 UTC, Mazayw commented on src/components/common/icons/LogoFooter.tsx
> +    height={124}
Достатньо 1 раз прописати fill="currentColor" і прибрати з усіх path

2023-07-21 16:16 UTC, Mazayw commented on src/types/typesAPI.d.ts
> +    phone1: String | Number;
телефони - Number

2023-07-21 16:16 UTC, Mazayw commented on src/types/typesAPI.d.ts
> +    linkedin: Url;
Чому Url?  Це ж String

2023-07-21 16:16 UTC, Mazayw commented on src/utils/API/contacts.ts
> +  // update({ contacts }: TContactsInfo) {
чому закоментовано?

2023-07-21 18:10 UTC, Neschadin commented on src/types/typesAPI.d.ts
> +    linkedin: Url;
це url !

2023-07-21 18:14 UTC, Mazayw commented on src/types/typesAPI.d.ts
> +    linkedin: Url;
![image](https://github.com/baza-trainee/baza-trainee-landing/assets/20990494/a2b84d54-1f50-4ae6-a8d7-cd49d1d59a61)
там тип string а не об'єкт Url

2023-07-23 08:57 UTC, Neschadin commented on src/utils/API/contacts.ts
> +  // update({ contacts }: TContactsInfo) {
скоріш за все взагалі видалю ці методи. бо футер, як серверна компонента, сам буде фетчити дані.

2023-07-23 09:04 UTC, Neschadin commented on src/types/typesAPI.d.ts
> +    linkedin: Url;
![image](https://github.com/baza-trainee/baza-trainee-landing/assets/73835274/6cde6c48-2bbf-4d6a-a195-24ec64059d5a)
з початку я прописав стрінгу. тс почав сваритись. глянув в саму комопненту, вона очікує урл, який в свою чергу і є стрінга або урлОбжект.  
більше не свариться )

2023-07-23 11:13 UTC, Mazayw commented on src/types/typesAPI.d.ts
> +    linkedin: Url;
Відповідно, в самій компоненті теж помилка)
Там лише стрінга, ніякого урл об'єкта

2023-07-23 11:13 UTC, Mazayw commented on src/utils/API/contacts.ts
> +  // update({ contacts }: TContactsInfo) {
Ці методи для адмінки

2023-07-23 15:55 UTC, Mazayw approved these changes

2023-07-23 15:56 UTC, Mazayw approved these changes

2023-07-23 15:58 UTC, Neschadin approved these changes

2023-07-23 15:58 UTC, merged