Atomic elements
bazaTraineeUkraine/baza-trainee pull request #47
Opened 2023-07-12 13:59 UTC by Mazayw

Add atomic components: info windows and admin title component

2023-07-12 18:30 UTC, Neschadin requested changes

2023-07-12 18:30 UTC, Neschadin commented on src/components/atomic/AlertWindow.tsx
> +            </div>
ці елементи онлі баттон. ти ж по діву клавіатурою не клацнеш, губиться аксесибіліті.

2023-07-12 18:30 UTC, Neschadin commented on src/components/atomic/AlertWindow.tsx
> +  };
мені здається це взагалі зайве. ти ж хенделри "готові" будеш в компонент передавати. тобто одразу в `onClick={onOkClickHandler}` назначай.

2023-07-12 18:30 UTC, Neschadin commented on src/components/atomic/AlertWindow.tsx
> +            </div>
не принципово в адміці, але для хорошого тону якйись текстовий тег краще `<h2>` , `<p>` , etc

2023-07-12 18:30 UTC, Neschadin commented on src/components/atomic/AlertWindow.tsx
> +            </div>
`<span>`

2023-07-12 18:34 UTC, Mazayw commented on src/components/atomic/AlertWindow.tsx
> +  };
Там же різні хендлери для "ок" і "скасувати"
Як їх передати разом?)

2023-07-12 18:34 UTC, Mazayw commented on src/components/atomic/AlertWindow.tsx
> +            </div>
Так, це я погарячкував)

2023-07-12 18:37 UTC, Mazayw commented on src/components/atomic/AlertWindow.tsx
> +            </div>
h2+

2023-07-12 18:38 UTC, Mazayw commented on src/components/atomic/AlertWindow.tsx
> +            </div>
Якщо семантика  - краще <p>

2023-07-13 10:31 UTC, Neschadin approved these changes

2023-07-13 10:31 UTC, merged