Made languages switcher for landing page, fixed bug#72
bazaTraineeUkraine/baza-trainee pull request #91
Opened 2023-08-06 18:25 UTC by WILSONPLUR

2023-08-20 23:00 UTC, Mazayw requested changes

2023-08-20 23:00 UTC, Mazayw commented on src/app/[lang]/dictionaries.ts
> +export const getDictionary = async (locale: string) =>
Для чого окрема функція для вибору словника?

2023-08-20 23:00 UTC, Mazayw commented on src/app/[lang]/not-found.tsx
Немає перекладу

2023-08-20 23:00 UTC, Mazayw commented on src/app/[lang]/page.tsx
Повинен бути SSR для всіх мов

2023-08-20 23:00 UTC, Mazayw commented on src/app/page.tsx
> +  useEffect(() => {
Для чого тут useEffect?

2023-08-20 23:00 UTC, Mazayw commented on src/components/MainPage/Header/index.tsx
> +  const pathname = headersList.get('x-invoke-path') || '';
Для чого?

2023-08-20 23:00 UTC, Mazayw commented on src/app/[lang]/page.tsx
> +      <Header navLinks={navLinks} />
Для чого навігацію виносити сюди?

2023-08-20 23:00 UTC, Mazayw commented on src/components/MainPage/Header/LanguageSelector.tsx
> +  const handleLangSwitch = (e: FormEvent, lang: TLandingLanguage) => {
Навіщо ця функція?

2023-08-20 23:00 UTC, Mazayw commented on src/components/MainPage/HeroSlider/SingleSlide.tsx
> +  slideLang: 'en' | 'pl' | 'ua';
Тип який часто повторюється краще винести в окрему змінну

2023-08-20 23:00 UTC, Mazayw commented on src/components/MainPage/HeroSlider/slides.ts
Те що буде братися з беку - краще відразу імітувати отримання даних. І робити відповідний об'єкт з мовами, як на беку

2023-08-20 23:00 UTC, Mazayw commented on src/components/MainPage/Modal/ContentDonate.tsx
> +  const paymentAmountData = [
Не варто робити переклад чисел/цифр

2023-08-20 23:00 UTC, Mazayw commented on src/components/MainPage/ModalParams.tsx
> +          href={pathname}
Для чого?

2023-08-20 23:00 UTC, Mazayw commented on src/components/MainPage/Partners/index.tsx
> +export const Partners = ({ dict }: { dict: TDictionary }) => {
Яке призначення пропсів?

2023-08-20 23:00 UTC, Mazayw commented on src/components/MainPage/Projects/ProjectCard/ProjectTeamMembers.tsx
> +    .sort((a, b) => a.user?.name?.localeCompare(b?.user?.name));
Для чого?

2023-08-20 23:00 UTC, Mazayw commented on src/components/MainPage/Projects/projects.ts
Це йфайл не повинен змінюватися

2023-08-20 23:00 UTC, Mazayw commented on src/components/MainPage/Reviews/slides.ts
> +  dict.reviews.list.map((listItem, i) => {
Ця інформація не повинна зберігатися на фронті

2023-08-20 23:00 UTC, Mazayw commented on src/types/commonTypes.d.ts
> +export type TDictionary = {
Якщо є об'єкт, не варто прописувати тип дного об'єкту окремо

2023-08-20 23:00 UTC, Mazayw commented on src/utils/developmentTimeCalculator.ts
Ця формула розроблялася для укр. мови. Для інших мов потрібно дивитися граматику

2023-08-21 10:51 UTC, WILSONPLUR commented on src/app/page.tsx
> +  useEffect(() => {
> Для чого тут useEffect?

Краще через next.config.js зробити редірект?

2023-08-21 10:55 UTC, WILSONPLUR commented on src/components/MainPage/ModalParams.tsx
> +          href={pathname}
> Для чого?

Фікс моменту, щоб коли закриваєш модальне вікно з документом зберігалась мова у url

2023-08-21 10:59 UTC, WILSONPLUR commented on src/components/MainPage/Modal/ContentDonate.tsx
> +  const paymentAmountData = [
> Не варто робити переклад чисел/цифр

Так, це перероблю, і справді, можна було просто переклад валюти додати і все

2023-08-21 10:59 UTC, WILSONPLUR commented on src/components/MainPage/Projects/projects.ts
> Це йфайл не повинен змінюватися

ок

2023-08-21 11:03 UTC, WILSONPLUR commented on src/components/MainPage/Reviews/slides.ts
> +  dict.reviews.list.map((listItem, i) => {
> Ця інформація не повинна зберігатися на фронті

Добре, але поки працював з "mock" даними й перекладом до них

2023-08-21 11:03 UTC, WILSONPLUR commented on src/components/MainPage/Projects/ProjectCard/ProjectTeamMembers.tsx
> +    .sort((a, b) => a.user?.name?.localeCompare(b?.user?.name));
> Для чого?

Були помилки

2023-08-21 11:04 UTC, WILSONPLUR commented on src/components/MainPage/HeroSlider/SingleSlide.tsx
> +  slideLang: 'en' | 'pl' | 'ua';
> Тип який часто повторюється краще винести в окрему змінну

Я й виніс, просто забув його тут використати

2023-08-21 11:06 UTC, Mazayw commented on src/app/page.tsx
> +  useEffect(() => {
Без useEffect теж буде працювати

2023-08-21 11:07 UTC, WILSONPLUR commented on src/app/[lang]/dictionaries.ts
> +export const getDictionary = async (locale: string) =>
> Для чого окрема функція для вибору словника?

І справді, тільки помилки від неї

2023-08-21 11:09 UTC, WILSONPLUR commented on src/components/MainPage/Header/index.tsx
> +  const pathname = headersList.get('x-invoke-path') || '';
> Для чого?

Вирішення багу з кліком на лого

2023-08-21 11:20 UTC, WILSONPLUR commented on src/app/[lang]/page.tsx
> +      <Header navLinks={navLinks} />
> Для чого навігацію виносити сюди?

Краще у самому Header це тримати?

2023-08-26 08:35 UTC, whoheywhat commented on src/components/MainPage/Partners/index.tsx
> +export const Partners = ({ dict }: { dict: TDictionary }) => {
Для того, щоб отримати інстанс dictionary або dict і успішно підставити переклад. Оскільки, [lang]/page.tsx - server side, то єдиний варіант передати пропс компоненту, в цьому випадку, Partners.

2023-08-26 08:38 UTC, WILSONPLUR commented on src/components/MainPage/Partners/index.tsx
> +export const Partners = ({ dict }: { dict: TDictionary }) => {
"dict" потрібен для того щоб відобразити потрібний переклад. Оскільки, [lang]/page.tsx - server-side, то єдиний варіант - пропс для, в цьому прикладі, Partners

2023-09-04 18:16 UTC, closed without merging

2023-09-04 18:17 UTC, Mazayw commented
not relevant